name: 'Terraform'

on: push

env:
  TF_LOG: INFO
  TF_INPUT: false
  TF_TOKEN: ${{ secrets.TF_TOKEN }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is 
    # ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure Terraform Cloud credentials
      run: |
        mkdir -p ~/.terraform.d
        cat > ~/.terraform.d/credentials.tfrc.json <<EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ secrets.TF_TOKEN }}"
            }
          }
        }
        EOF

    - name: Terraform Init
      env:
        # for app.terraform.io, Terraform will look for TF_TOKEN_app_terraform_io
        TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
      run: terraform init -input=false -no-color


    # …follow with plan/apply steps as usual



    # Run a terraform fmt for push
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    # Run a terraform validate
    # Run even if formatting fails
    - name: Terraform Validate
      id: validate
      if: (success() || failure())
      run: terraform validate
